In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

from sklearn.metrics import root_mean_squared_error, r2_score
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error

### Loading the saved decisiontree model

In [48]:
dt_model = joblib.load('decisiontree_model.pkl')

In [49]:
X_test = pd.read_csv('splits/X_test_dataset.csv')

In [50]:
X_test

,Inches,Ram,Weight,Touchscreen,Ips,HD,Company_Acer,Company_Apple,Company_Asus,Company_Dell,...,gpu_name_Intel HD,gpu_name_Intel UHD,gpu_name_Nvidia GeForce,gpu_name_Nvidia Quadro,gpu_name_Other,Memory_Type_Flash Storage,Memory_Type_HDD,Memory_Type_Hybrid,Memory_Type_Other,Memory_Type_SSD
0,15.6,4,2.180,0,0,0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,14.0,4,1.760,0,0,0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,14.0,16,1.950,0,0,1,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,13.5,8,1.252,1,0,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,14.0,8,1.420,1,1,0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,15.6,4,2.400,0,0,1,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
192,15.6,2,2.190,0,0,0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
193,17.3,16,2.900,0,0,1,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
194,14.0,16,1.140,0,1,1,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
195,15.6,8,2.100,0,1,1,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [51]:
y_test = pd.read_csv('splits/y_test_dataset.csv')

In [52]:
y_test

            Price
0     85221.73296
1    141194.66400
2    654357.78720
3    349311.85848
4    435739.82400
..            ...
191   93319.38720
192   37215.54720
193  379448.97120
194  458181.36000
195  214036.14960

[196 rows x 1 columns]

### Price prediction on test

In [53]:
y_test_pred = dt_model.predict(X_test)

In [54]:
y_test_pred

array([  87076.899936,  163636.2     ,  514098.1872  ,  336436.0272  ,
        306139.9536  ,  616217.773392,   74337.588   ,  423833.3424  ,
        132592.0752  ,  224228.3472  ,  204592.0032  ,  313526.024136,
        168124.5072  ,  423833.3424  ,  134462.2032  ,   77610.312   ,
         95189.5152  ,  282950.3664  ,  356818.552272,  528124.1472  ,
        367604.8272  ,  168124.5072  ,  239189.3712  ,  187012.8     ,
         37215.5472  ,   55542.8016  ,  158306.3352  ,  168124.5072  ,
         54607.7376  ,  336436.0272  ,  252280.2672  ,  314181.504   ,
        115199.8848  ,  106410.2832  ,  242929.6272  ,  304643.8512  ,
         65267.4672  ,  203843.952   ,  261069.8688  ,  200477.7216  ,
        155594.6496  ,  155594.6496  ,  355324.32    ,   93319.3872  ,
         85838.8752  ,   39085.6752  ,  239189.3712  ,   37215.5472  ,
        203843.952   ,  126673.12008 ,   74337.588   ,  289054.464192,
        131282.9856  ,  684354.64032 ,  106410.2832  ,   65080.4544  ,
         89558.559792,   51426.649872,  183085.5312  ,  457994.3472  ,
        461360.5776  ,  429942.4272  ,  128101.897872,  138202.4592  ,
        484363.152   ,  170368.6608  ,  224228.3472  ,  264436.0992  ,
        148488.1632  ,  274534.7904  , 1084487.2272  ,  312685.4016  ,
        184955.6592  ,  128851.8192  , 1084487.2272  ,  164571.264   ,
        262098.4392  ,   89558.559792,   87709.0032  ,  217308.8736  ,
         55729.8144  ,  183085.5312  ,  137454.408   ,  166254.3792  ,
        190564.173072,   74618.1072  ,  467344.9872  ,  291926.9808  ,
         90701.208   ,  204966.0288  ,  295293.2112  ,  140072.5872  ,
        210202.3872  ,  111833.6544  ,  130721.9472  ,  448456.6944  ,
         55729.8144  ,  143588.42784 ,  190753.056   ,  304643.8512  ,
         85838.8752  ,  119501.1792  ,  155407.6368  ,  160831.008   ,
        148860.318672,  287511.608592,  280519.2     ,  326711.3616  ,
        334752.912   ,   74618.1072  ,  176353.0704  ,  121558.32    ,
        347095.7568  ,  467344.9872  ,  579739.68    ,  244051.704   ,
         64332.4032  ,   90701.208   ,  102047.274576,  355137.3072  ,
        183085.5312  ,   70410.3192  ,  275843.88    ,  168105.80592 ,
        237880.2816  ,  200103.696   ,   79667.4528  ,  257890.6512  ,
        137454.408   ,  212259.528   ,  297350.352   ,  102855.169872,
        256188.83472 ,  184207.608   ,  190192.0176  ,   54027.99792 ,
        168124.5072  ,  200197.2024  ,  128066.36544 ,   91391.285232,
        276591.9312  ,  239189.3712  ,   73664.34192 ,  213718.22784 ,
        233627.610528,  317921.76    ,  145869.984   ,  616217.773392,
        264436.0992  ,   87710.873328,  461360.5776  ,  105662.232   ,
         70877.8512  ,   59657.0832  ,  252280.2672  ,  383715.668232,
        355324.32    ,   90701.208   ,   83031.813072,  142877.7792  ,
        428257.441872,  200197.2024  ,  204995.950848,   86007.18672 ,
        128851.8192  ,  226846.5264  ,  205712.209872,  175979.0448  ,
        168105.80592 ,  112020.6672  ,  266867.2656  ,  106410.2832  ,
        194306.2992  ,  164384.2512  ,  107083.52928 ,  254489.3559  ,
        299033.4672  ,  112020.6672  ,  218243.9376  ,  152041.4064  ,
        237319.2432  ,  136332.3312  ,   74337.588   ,  198233.568   ,
        249475.0752  ,  291552.9552  ,  450326.8224  ,  355137.3072  ,
        309506.184   ,  106410.2832  ,   93319.3872  ,   77597.84448 ,
         61714.224   ,  382147.565904,  355324.32    ,  242929.6272  ])

### Finding RMSE from actual y values and predicted y values on test

In [55]:
root_mean_squared_error(y_test, y_test_pred)

90861.2465370372

### Finding MAE from actual y values and predicted y values on test

In [56]:
mean_absolute_error(y_test, y_test_pred)

49330.311920632645

### Finding R² scrore from actual y values and predicted y values on test

In [57]:
r2_score(y_test, y_test_pred)

0.6286594007616595

### Finding MAPE from actual y values and predicted y values on test

In [58]:
mean_absolute_percentage_error(y_test, y_test_pred) * 100

20.442801861900136

### Finding model accuracy from actual x and y values on test

In [59]:
dt_model.score(X_test, y_test)

0.6286594007616595