In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

from sklearn.metrics import root_mean_squared_error, r2_score
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error

### Loading the saved decisiontree model

In [2]:
dt_model = joblib.load('decisiontree_model.pkl')

In [3]:
X_val = pd.read_csv('splits/X_validation_dataset.csv')

In [4]:
X_val

,Inches,Ram,Weight,Touchscreen,Ips,HD,Company_Acer,Company_Apple,Company_Asus,Company_Dell,...,gpu_name_Intel HD,gpu_name_Intel UHD,gpu_name_Nvidia GeForce,gpu_name_Nvidia Quadro,gpu_name_Other,Memory_Type_Flash Storage,Memory_Type_HDD,Memory_Type_Hybrid,Memory_Type_Other,Memory_Type_SSD
0,12.5,8,1.60,0,0,1,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,13.3,8,1.34,0,0,0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,15.6,4,2.20,0,0,1,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,15.6,8,2.20,0,0,0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,17.3,8,2.80,0,0,0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,15.6,4,1.96,0,0,0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
163,15.0,4,2.08,1,0,1,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
164,15.6,8,2.50,0,1,1,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
165,17.3,8,2.50,0,0,1,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
166,14.0,4,1.64,0,0,0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [5]:
y_val = pd.read_csv('splits/y_validation_dataset.csv')

In [6]:
y_val

            Price
0    316051.63200
1    216691.73136
2    119501.17920
3    209267.32320
4    130534.93440
..            ...
162   93319.38720
163   95189.51520
164  222358.21920
165  172612.81440
166  145682.97120

[167 rows x 1 columns]

### Price prediction on validation

In [7]:
y_val_pred = dt_model.predict(X_val)

In [8]:
y_val_pred

array([ 149238.084528 ,  168113.286432 ,  134709.060096 ,  261630.9072   ,
        189255.083472 ,  429942.4272   ,  298191.9096   ,  141942.7152   ,
        256188.83472  ,   74618.1072   ,  383170.52592  ,  128101.897872 ,
        217308.8736   ,  425828.1456   ,  121558.32     ,  297350.352    ,
        164386.121328 ,  390856.752    ,  128066.36544  ,   89392.1184   ,
         78291.038592 ,   42825.9312   ,  228902.732136 ,  100799.8992   ,
        382147.565904 ,  400201.781616 ,   69007.7232   ,  209437.504848 ,
        182711.5056   ,  820799.1792   ,  399272.328    ,  153163.4832   ,
         55729.8144   ,   87076.899936 ,  213568.6176   ,  169994.6352   ,
         93319.3872   ,  205527.0672   ,   93319.3872   ,   47194.550208 ,
        117818.064    ,  126673.12008  ,   87521.9904   ,  439293.0672   ,
        262098.4392   ,  261630.9072   ,  237132.2304   ,  162514.1232   ,
        224228.3472   ,   64517.545872 ,  128101.897872 ,  222732.2448   ,
        188978.304528 ,  136332.3312   ,  467344.9872   ,   57225.9168   ,
        183085.5312   ,  119501.1792   ,   87709.0032   ,  104540.1552   ,
        203843.952    ,  100799.8992   ,  358592.056992 ,  484363.152    ,
         77597.84448  ,  102670.0272   ,  194306.2992   ,  242929.6272   ,
        356818.552272 ,  224228.3472   ,  228529.6416   ,   65267.4672   ,
        579739.68     ,   99116.784    ,  220488.0912   ,  168124.5072   ,
        110150.5392   ,  175754.62944  ,   42825.9312   ,   55729.8144   ,
        275843.88     ,  336436.0272   ,  138763.4976   ,   42825.9312   ,
        286877.6352   ,  194306.2992   ,  153163.4832   ,  234509.843412 ,
        117818.064    ,  194306.2992   ,  220488.0912   ,  327066.68592  ,
        183272.544    ,  221690.583504 ,  134462.2032   ,  119501.1792   ,
        111646.6416   ,  304643.8512   ,  167563.4688   ,   72747.9792   ,
        122493.384    ,   55729.8144   ,  222732.2448   ,  109402.488    ,
        237132.2304   ,   42825.9312   ,  188695.9152   ,  177475.1472   ,
        201973.824    ,  420905.968704 ,  320210.4226464,   97925.512464 ,
        109215.4752   ,  176353.0704   ,  228529.6416   ,   72747.9792   ,
        579739.68     ,  164384.2512   ,  205527.0672   ,  170368.6608   ,
        158773.8672   ,   95189.5152   ,  106971.3216   ,  490908.6      ,
        284352.9624   ,  111646.6416   ,   91391.285232 ,  119463.77664  ,
         46566.1872   ,  233627.610528 ,  239376.384    ,  171864.7632   ,
        220488.0912   ,  420905.968704 ,   64332.4032   ,   82098.6192   ,
        166254.3792   ,  347095.7568   ,  195697.674432 , 1084487.2272   ,
         89392.1184   ,   72747.9792   ,  190753.056    ,  264267.78768  ,
         64704.558672 ,  355324.32     ,  244051.704    ,  457994.3472   ,
        413608.729248 ,  168124.5072   ,  109215.4752   ,   57225.9168   ,
         93538.192176 ,  158942.17872  ,  223106.2704   ,  342046.4112   ,
        266867.2656   ,  195697.674432 ,  119501.1792   ,  223667.3088   ,
        367604.8272   ,  304643.8512   ,   73664.34192  ,   90136.429344 ,
        212321.8656   ,  201973.824    ,  187012.8      ])

### Finding RMSE from actual y values and predicted y values on validation

In [9]:
root_mean_squared_error(y_val, y_val_pred)

78817.81181850153

### Finding MAE from actual y values and predicted y values on validation

In [10]:
mean_absolute_error(y_val, y_val_pred)

45634.12865620599

### Finding R² scrore from actual y values and predicted y values on validation

In [12]:
r2_score(y_val, y_val_pred)

0.5647990408695115

### Finding MAPE from actual y values and predicted y values on validation

In [13]:
mean_absolute_percentage_error(y_val, y_val_pred) * 100

20.9836930412426

### Finding model accuracy from actual x and y values on validation

In [14]:
dt_model.score(X_val, y_val)

0.5647990408695115